CREATE TABLE RAGHUL_EMPLOYEES 
( 
ID INT PRIMARY KEY, 
FIRST_NAME VARCHAR(40), 
LAST_NAME VARCHAR(40), 
SALARY DECIMAL(8,2), 
DEPARTMENT_ID INT, 
YEAR_OF_JOINING DATETIME, 
YEAR_OF_RELIEVING DATETIME 
) 
CREATE TABLE RAGHUL_DEPARTMENTS 
( 
DEPARTMENT_ID INT PRIMARY KEY, 
MANAGER_ID INT, 
DEPARTMENT_NAME VARCHAR(50) 
)
insert into RAGHUL_EMPLOYEES values(001,'Raghul','S',52000.00,101,'09-01-1999','12-12-2001');
insert into RAGHUL_EMPLOYEES values(002,'abi','S',60000.00,102,'09-10-1999','12-22-2009');
insert into RAGHUL_EMPLOYEES values(003,'deepika','S',25000.00,103,'10-01-1995','12-29-2020');
insert into RAGHUL_EMPLOYEES values(004,'subha','S',58000.00,101,'03-01-1996','12-31-2011');
insert into RAGHUL_EMPLOYEES values(005,'bhanu','S',38000.00,103,'09-11-1992','12-30-2002');
insert into RAGHUL_EMPLOYEES values(006,'Ram','S',45000.00,102,'07-01-1990','12-25-2001');
insert into RAGHUL_EMPLOYEES values(007,'kalees','S',32000.00,101,'09-01-1999','12-18-2000');
insert into RAGHUL_EMPLOYEES values(008,'selva','S',65000.00,104,'09-01-1999','12-21-2017');
insert into RAGHUL_EMPLOYEES values(009,'anish','S',72000.00,102,'09-01-1999','10-12-2016');
insert into RAGHUL_EMPLOYEES values(010,'arun','S',59000.00,104,'04-01-1990','12-02-2011');
insert into RAGHUL_EMPLOYEES values(011,'ilakkiyaa','S',80000.00,103,'05-05-1996','12-12-2022');
select * from RAGHUL_EMPLOYEES;
insert into RAGHUL_DEPARTMENTS values (101,011,'Developer');
insert into RAGHUL_DEPARTMENTS values (102,009,'Testing');
insert into RAGHUL_DEPARTMENTS values (103,001,'Admin');
insert into RAGHUL_DEPARTMENTS values (104,005,'Sales');
select * from RAGHUL_DEPARTMENTS;
select FIRST_NAME from RAGHUL_EMPLOYEES where FIRST_NAME like's%';
select FIRST_NAME from RAGHUL_EMPLOYEES where FIRST_NAME like's%n';
select * from RAGHUL_EMPLOYEES where FIRST_NAME like's%' and  DEPARTMENT_ID in (102);
select DEPARTMENT_ID from RAGHUL_DEPARTMENTS where DEPARTMENT_ID like'_2%';
select * from RAGHUL_EMPLOYEES where DEPARTMENT_ID in (102,101,103);
select * from RAGHUL_EMPLOYEES where SALARY between 40000 and 50000;
select FIRST_NAME,SALARY,RAGHUL_EMPLOYEES.DEPARTMENT_ID,MANAGER_ID from RAGHUL_EMPLOYEES inner join RAGHUL_DEPARTMENTS on RAGHUL_EMPLOYEES.DEPARTMENT_ID=RAGHUL_DEPARTMENTS.DEPARTMENT_ID where MANAGER_ID is null; 
select * from RAGHUL_EMPLOYEES order by FIRST_NAME;
select FIRST_NAME,SALARY,DEPARTMENT_ID from RAGHUL_EMPLOYEES order by DEPARTMENT_ID,SALARY desc;
select LEFT(FIRST_NAME,3) from RAGHUL_EMPLOYEES ;
select RIGHT(LAST_NAME,2) from RAGHUL_EMPLOYEES ;
select FIRST_NAME,Charindex('a',FIRST_NAME) as POSITION  from RAGHUL_EMPLOYEES;
select Max(SALARY) As Maximum_Salary from RAGHUL_EMPLOYEES;
select e1.SALARY from RAGHUL_EMPLOYEES e1 where(select count(distinct e2.SALARY) from RAGHUL_EMPLOYEES e2 where e1.SALARY<e2.SALARY)=2-1;
select avg(SALARY) As Average_Salary from RAGHUL_EMPLOYEES where DEPARTMENT_ID=102;
select Count(*) as Count,year(YEAR_OF_JOINING)as year from RAGHUL_EMPLOYEES where DEPARTMENT_ID in(102) group by year(YEAR_OF_JOINING);
select datename (month,YEAR_OF_JOINING)as month from RAGHUL_EMPLOYEES group by datename (month,YEAR_OF_JOINING)having count (ID)>5;
select avg(SALARY) avg from RAGHUL_EMPLOYEES where YEAR_OF_RELIEVING < GETDATE();
select LAST_NAME, YEAR_OF_JOINING from RAGHUL_EMPLOYEES where YEAR_OF_JOINING between '01-01-1995' and '12-31-2000';
select datename (year,YEAR_OF_JOINING)as year from RAGHUL_EMPLOYEES group by datename (year,YEAR_OF_JOINING)having count (ID)>3;
select ID from RAGHUL_EMPLOYEES WHERE 50000 < (select avg(SALARY) from RAGHUL_EMPLOYEES);
select ID,DATEDIFF(day,YEAR_OF_JOINING,YEAR_OF_RELIEVING) as days from RAGHUL_EMPLOYEES; 
select ID from RAGHUL_EMPLOYEES where year(YEAR_OF_JOINING)=year(GETDATE());
select UPPER (FIRST_NAME),LOWER(LAST_NAME) from RAGHUL_EMPLOYEES;
select len(FIRST_NAME),FIRST_NAME from RAGHUL_EMPLOYEES where FIRST_NAME like '___%a%';
select FIRST_NAME, YEAR(YEAR_OF_RELIEVING)-year(YEAR_OF_JOINING) experience from RAGHUL_EMPLOYEES;
select  FIRST_NAME from RAGHUL_EMPLOYEES where datename(month,YEAR_OF_JOINING)='May';

select FIRST_NAME,LAST_NAME,ID from RAGHUL_EMPLOYEES where SALARY>(select avg(SALARY) from RAGHUL_EMPLOYEES);
CREATE VIEW EMPLOYEES_RECORDS As select ID,FIRST_NAME,LAST_NAME, 
e.DEPARTMENT_ID,DEPARTMENT_NAME from RAGHUL_EMPLOYEES e inner join RAGHUL_DEPARTMENTS d on e.DEPARTMENT_ID=d.DEPARTMENT_ID;
select*from EMPLOYEES_RECORDS;
SELECT * FROM RAGHUL_EMPLOYEES
update RAGHUL_EMPLOYEES set YEAR_OF_RELIEVING = null where ID=007;
update RAGHUL_EMPLOYEES set LAST_NAME= null where ID=009;
select * from RAGHUL_EMPLOYEES;
update RAGHUL_EMPLOYEES set LAST_NAME= null where ID=009;
update RAGHUL_EMPLOYEES set LAST_NAME ='AAA' where  ID=009;
CREATE synonym ILAKKIYAA_EMPLOYEES for RAGHUL_EMPLOYEES;
select * from ILAKKIYAA_EMPLOYEES;
create procedure BETWEEN_DATES
as
select ID from RAGHUL_EMPLOYEES where YEAR_OF_JOINING between '09-01-1995' and '10-10-1999'
go
exec BETWEEN_DATES ;
create procedure INSERT_ROWS
as
insert into RAGHUL_DEPARTMENTS values(105,007,'Finance');
go
exec INSERT_ROWS;
select replace(convert(varchar,'2006-12-30',101),'-','')+ replace(convert(varchar,'00:38:54',108),':','');
--primary key
CREATE TABLE RAGHUL_DEPARTMENTS 
( 
DEPARTMENT_ID INT PRIMARY KEY, 
MANAGER_ID INT, 
DEPARTMENT_NAME VARCHAR(50) 
)
--foreign key
CREATE TABLE RAGHUL_EMPLOYEES 
( 
ID INT PRIMARY KEY, 
FIRST_NAME VARCHAR(40), 
LAST_NAME VARCHAR(40), 
SALARY DECIMAL(8,2), 
DEPARTMENT_ID INT foreign key REFERENCES RAGHUL_EMPLOYEES , 
YEAR_OF_JOINING DATETIME, 
YEAR_OF_RELIEVING DATETIME 
) 
select DEPARTMENT_NAME FROM RAGHUL_EMPLOYEES INNER JOIN RAGHUL_DEPARTMENTS ON RAGHUL_EMPLOYEES.DEPARTMENT_ID=RAGHUL_DEPARTMENTS.DEPARTMENT_ID GROUP BY DEPARTMENT_NAME HAVING AVG(SALARY)>10000;